### ISSUE TITLE
Exiting fullscreen changes monitors

### ISSUE THREAD

**Issue by RodolfoFigueroa** [jellyfin/jellyfin-media-player#393] opened 2023-03-11 01:10 UTC
**Describe the bug**
When using two or more monitors on Windows, one has to be tagged as the "main" monitor in the system settings. If the player is playing on fullscreen on the non-main display, and the user exits fullscreen, the player automatically transfers to the main display.

**To Reproduce**
1. Identify the main and non-main display in System settings -> Change the resolution of the display.
2. Open Jellyfin Media Player, move it to the non-main display, play some media and make it fullscreen.
3. Exit fullscreen.
4. The player should automatically move to the main display.

**Expected behavior**
The player should remain in the same display it was when exiting fullscreen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.8.1
 - Installation Method: Windows installer

[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10947150/JellyfinMediaPlayer.log)

**Comment by iwalton3** [comment] 2023-03-12 16:18
Duplicate of #245

**Closed by iwalton3** 2023-03-12 16:18 UTC
Labels: bug
