### ISSUE TITLE
Rich Presence 

### ISSUE THREAD

**Issue by ohitstom** [jellyfin/jellyfin-media-player#330] opened 2022-10-29 23:33 UTC
Is there any news on the implementation of rich presence?
My first attempt was to try and add it to the mpv config for jmp as there are plugins for mpv that do this.

However that didnt work and i am now using MBCord but that is less than perfect seeing its a background program i have to run that might fall out of support at any minute.

Is there any movement on this issue? It would be awesome seeing as the only jellyfin related clients that support this are j-mpv-shim
which again is a good implementation but having to launch a web browser then cast to mpv is a huge pain.

With mbcord being entirely javascript and this media player being (im assuming) cef based, i was hoping this wouldnt be too hard of an integration for someone to port over.

**Comment by iwalton3** [comment] 2023-02-16 01:33
Duplicate of #45

**Closed by iwalton3** 2023-02-16 01:33 UTC
Labels: enhancement
