### ISSUE TITLE
MacOS 1.14 and below NOT SUPPORTED

### ISSUE THREAD

**Issue by PxBCPG** [jellyfin/jellyfin-media-player#66] opened 2021-04-25 07:45 UTC
# MacOS 1.14 and below NOT SUPPORTED

Hi ! 

I've tried to install the desktop app on my Mac, which runs macOS Mojave, but I wasn't able to install it because the app is only supported on macOS 1.15+

Please change this :pray:

**Comment by PxBCPG** [comment] 2021-04-25 07:45
PS : not really a bug, but not a feature request either...

**Comment by crobibero** [comment] 2021-04-25 13:35
Duplicate of https://github.com/jellyfin/jellyfin-media-player/issues/46

**Closed** 2021-04-25 14:14 UTC
Labels: bug
