### ISSUE TITLE
When switching to a second server, the content of the switched to server is only shown after a refresh

### ISSUE THREAD

**Issue by Echtze1t** [jellyfin/jellyfin-media-player#647] opened 2024-05-18 11:42 UTC
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/15362993/JellyfinMediaPlayer.log)

After switching the server (both are 10.9.1, one is on Windows, one on Linux), the switch is successful, but the content shown is still from the old server. You have to refresh the page to see the content of the switched to sever.

1. Click hamburger
2. Click "Select Server"
3. Choose second server

**Expected behavior**
Well, to see the content of the switched to server right away.

**Screenshots**
1) Select server
![1 Select Server](https://github.com/jellyfin/jellyfin-media-player/assets/25301944/f2de3ed5-4a56-497d-a14c-510400a9fe84)
2) Choose second server and switch
![2 Choose Second Server](https://github.com/jellyfin/jellyfin-media-player/assets/25301944/5c92ac71-04da-4f95-a34f-a639ef8c44eb)
3) Switch successful, but content of switched from server still shown
![3 New Server, Same Content Shown](https://github.com/jellyfin/jellyfin-media-player/assets/25301944/171866fd-4fae-48fb-b673-f8be157f2691)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.10.0
 - Installation Method; windows installer

**Comment by thornbill** [comment] 2024-05-19 14:06
Looks like a duplicate of #639

**Closed** 2024-05-19 14:07 UTC
Labels: bug, duplicate

**Comment by Echtze1t** [comment] 2024-05-19 14:55
> Looks like a duplicate of #639

Oh, very sorry. I was reading through all the latest issues, but somehow must have missed this.
