### ISSUE TITLE
Unable to playback any file types after upgrade from 1.71 to 1.81

### ISSUE THREAD

**Issue by SpaghettiEnforcer** [jellyfin/jellyfin-media-player#384] opened 2023-02-25 16:42 UTC
**Describe the bug**
Windows Player works without any issues on 1.71, but when I upgrade to 1.81 nothing will play. All video and audio file types fail to play. On Linux, using the flatpak, everything continues to run as expected. When I uninstall the Windows 1.81 and reinstall 1.71, all my files play without issue. Something about the upgrade to 1.81 breaks the player.
The user I'm using has no restrictions and has the default settings for a non-admin user.

**To Reproduce**
1. Upgrade 1.71 to 1.81
2. Try to play an audio or video file
3. Fails
4. uninstall 1.81 and reinstall 1.71
5. try to play an audio or video file
6. Succeeds

**Expected behavior**
Upgrade to 1.81 and all media that ran properly under 1.71 runs properly under 1.81.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, latest updates
 - 64-bit version of Player

Logs from 1.81 being unable to play media attached.
[Jellyfin.log](https://github.com/jellyfin/jellyfin-media-player/files/10831727/Jellyfin.log)

**Comment by iwalton3** [comment] 2023-03-04 03:00
Duplicate of https://github.com/jellyfin/jellyfin-media-player/issues/375

**Closed by iwalton3** 2023-03-04 03:00 UTC
Labels: bug
