### ISSUE TITLE
Kanji support seems incomplete

### ISSUE THREAD

**Issue by Karmak23** [jellyfin/jellyfin-media-player#334] opened 2022-11-10 07:10 UTC
Kanji support in latest player (version 1.7.1 on up-to-date Arch Linux) seems incomplete. Its OK in most of the places, but display empty squares when onto media library thumbnails. I’ve NO custom CSS nor any customizations. See screenshots below :

**NOT OK**
![Capture d’écran du 2022-11-10 08-02-46](https://user-images.githubusercontent.com/663404/201023302-b524b3d3-e818-4e53-b6c2-cefe34a4a94d.png)

**OK as expected**
![Capture d’écran du 2022-11-10 08-03-11](https://user-images.githubusercontent.com/663404/201023338-231fa503-eba5-421c-8a2e-cdbbb03ce219.png)

**also OK as expected**
![Capture d’écran du 2022-11-10 08-04-12](https://user-images.githubusercontent.com/663404/201023377-7e49419c-b332-4805-bfdf-cd0edf577d17.png)

Could this be fixed by a simple CSS modification ? I don't know at all where to put them, I’m new to JF and didn't investigate the related docs yet.

**Comment by iwalton3** [comment] 2022-12-26 18:21
Does this happen on the regular web interface too? A quick look seems to suggest those images are generated by the Jellyfin server and not this client. The good news is you can replace the library thumbnails with whatever image you like, so there is at least a workaround.

**Comment by crobibero** [comment] 2023-01-28 11:26
Tgose images are generated by the server. Closing as duplicate of https://github.com/jellyfin/jellyfin/issues/5008

**Closed by crobibero** 2023-01-28 11:26 UTC
Labels: bug
