### ISSUE TITLE
Seeking doesn't work

### ISSUE THREAD

**Issue by snowl** [jellyfin/jellyfin-media-player#174] opened 2021-12-15 06:22 UTC
**Describe the bug**

Attempting to seek does nothing. Closing a video that's watched halfway seems to break it as well. It does not affect the web client.

**To Reproduce**
1. Watch a TV Show
2. Try and seek outside of the buffered zone
3. Close the TV Show
4. Try and re-open it

I'm aware there's something most likely wrong with my setup. I'm willing to let a jellyfin volunteer access my server to debug/test the issue.

**Expected behavior**
Seeking and replaying a server works.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.6.1
 - Installation Method: Windows Installer

- Server Hardware: Intel 11 NUC
- OS: Proxmox to Debian LXC 
- Jellyfin Version: 10.7.7
- Storage: Synology NAS
- Method of access: Samba
- Docker Image: linuxserver/docker
- Changes to Docker Image: https://github.com/linuxserver/docker-jellyfin/issues/109#issuecomment-972252368

**Additional context**
Log of it seeking once correctly then unable to seek: https://files.diaz.gg/NvsfO4.txt

Log of it unable to seek at all: https://files.diaz.gg/wUkN1h.txt

Log of it unable to re-start the stream: https://files.diaz.gg/Tepa5f.txt

**Comment by comfreak89** [comment] 2021-12-29 22:30
I have the pretty same issue when using the windows client from an device, which is external. I am using also Nginx as reverse proxy and can not seek with the windows client. However, it works with the android app and via browser without issues.

But it works when the device is in my internal network and using the windows client!

**Comment by LubricantJam** [comment] 2022-01-03 21:55
This is the same for me also, unable to seek/skip.

**Comment by zkhcohen** [comment] 2022-01-26 01:56
+1

Pretty wild that this bug snuck past QA...

**Comment by iwalton3** [comment] 2022-01-26 02:17
Apologies. I’m the only maintainer of this application and haven’t have a lot of time/energy lately. (“QA” testing is manual smoke testing by me before releases, but the recent prereleases will likely help. I do try to tackle major bugs quickly.)

Looking at the log above, it looks like it is direct playing and having an error with seeking in the stream (`mkv: Stream is not seekable or unknown size, not reading mkv metadata at end of file.`)

I am wondering if Nginx is somehow misconfigured to not allow range requests. See: https://stackoverflow.com/questions/22728016/nginx-is-not-accepting-range-of-bytes

That being said, I use an Nginx reverse proxy and don’t have this issue in either direct play or transcode mode. I’m skeptical that it’s a problem with Jellyfin Media Player and am more inclined to think direct play in general that is broken. (Which this client nearly always uses while many others always remux or transcode.)

Hope this helps.

**Comment by zkhcohen** [comment] 2022-01-26 21:45
This issue is unique to the Media Player _and_ the playback format.

> Looking at the log above, it looks like it is direct playing and having an error with seeking in the stream (`mkv: Stream is not seekable or unknown size, not reading mkv metadata at end of file.`)

I'm not able to reproduce the logs that the OP submitted, but I'm getting very similar results. 

> That being said, I use an Nginx reverse proxy and don’t have this issue in either direct play or transcode mode. I’m skeptical that it’s a problem with Jellyfin Media Player and am more inclined to think direct play in general that is broken. (Which this client nearly always uses while many others always remux or transcode.)

In my setup, I have Jellyfin routed through Traefik, and then Cloudflrae.

**Here's a matrix of my tests (all using the public URL):**

![image](https://user-images.githubusercontent.com/12313533/151251857-94891acf-241e-40dc-94e0-faf9b9ce111c.png)

Changing the URL to the private URL resolves the single failure: Direct Play + Jellyfin Media Player (MPV).

**Comment by comfreak89** [comment] 2022-01-26 21:50
I can agree with my tests with @zkhcohen - I am also using Cloudflare (with caching at Cloudflare disabled via rules) but Nginx as proxy with the official sugested nginx config (https://jellyfin.org/docs/general/networking/nginx.html).

I also checked for  "proxy_force_ranges off" and "max_ranges 0" in my nginx config - could not found it, so the link suggested by @iwalton3 does not apply for me.

**Comment by iwalton3** [comment] 2022-01-26 22:04
Alright to help narrow down what is happening, please do the following:
 - Open the media you wish to check.
 - Click the "Copy Stream URL" option.
 - You should get a URL that resembles this: `https://your-server.fake/Items/SOME_GUID/Download?api_key=SOME_KEY`
 - Change that URL to resemble this: `https://your-server.fake/Videos/SOME_GUID/stream?static=true`
 - Then attempt to open this URL in a local player. (For instance, good ones to try would be MPV and VLC.)

There is still a possibility that other players are playing the media by doing a remux and not by playing it directly, which could explain the discrepancy.

**Comment by zkhcohen** [comment] 2022-01-26 22:12
> * Open the media you wish to check.
> * Click the "Copy Stream URL" option.
> * You should get a URL that resembles this: `https://your-server.fake/Items/SOME_GUID/Download?api_key=SOME_KEY`
> * Change that URL to resemble this: `https://your-server.fake/Videos/SOME_GUID/stream?static=true`
> * Then attempt to open this URL in a local player. (For instance, good ones to try would be MPV and VLC.)

Using the method above I am able to stream/seek in both VLC and MPV using the public URL.

**Comment by sebtech33** [comment] 2022-01-31 12:14
I have the same problem. But seeking sometimes works. It works fine when using the stream url in vlc.

**Comment by comfreak89** [comment] 2022-02-08 21:13
Short feedback from me as I can not reproduce the issue anymore.

These are my changes:
- changed from LXC container to QEMU VM because
- I do transcoding on a Nvidia P400 with PCIe passthrough now (before that via CPU in the LXC container)
- I added the internal IP of my Nginx proxy to the admin settings under "Network" -> "Known Proxies" (I dont know the correct english translation as I have a german jellyfin)

I am using Proxmox as hypervisor.

**Comment by DesertCookie** [comment] 2022-03-04 15:09
The newest pre-releases did not make any change for me.

I too can play the file via VLC but as we are trying to use SyncPlay we cannot do that.

**Comment by iwalton3** [comment] 2022-03-31 03:34
Some CloudFlare users had success with the approach mentioned here: https://www.reddit.com/r/jellyfin/comments/tqre98/jellyfin_media_player_v170_prerelease_4_updated/i2o3vpr/?context=5

**Comment by d3vr** [comment] 2022-05-16 18:57
> Some CloudFlare users had success with the approach mentioned here: https://www.reddit.com/r/jellyfin/comments/tqre98/jellyfin_media_player_v170_prerelease_4_updated/i2o3vpr/?context=5

Changing Cloudflare's caching setting to `no query string` resolved the issue for me as well 🎉

**Comment by snowl** [comment] 2022-06-01 06:07
I can confirm that cloudflare also worked for me (the OP) :)

**Comment by laurinneff** [comment] 2022-11-07 20:45
My Jellyfin is also behind Cloudflare and the caching setting change solves the issue. @iwalton3, maybe pin this issue and add something like "Cloudflare users read this" to the title so that others find this more quickly?

**Comment by sevenrats** [comment] 2024-01-05 04:41
closing as a malconfiguration issue.

**Closed by sevenrats** 2024-01-05 04:41 UTC
Labels: bug
