### ISSUE TITLE
JMP 1.8.1 — ffmpeg requires TLS 1.2 to not return playback error

### ISSUE THREAD

**Issue by snozinho** [jellyfin/jellyfin-media-player#375] opened 2023-02-14 14:17 UTC
**Describe the bug**
After updating to JMP 1.8.1 any attempt to play any media gives a playback error.

**To Reproduce**
1. Update to JMP 1.8.1
2. Click on any media to try and play it
3. See error

**Expected behavior**
Play the media as it used to on version 1.7.1

**Screenshots**
https://media.discordapp.net/attachments/773650260903591946/1074982167270137886/image.png

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version: 1.8.1
 - Installation Method: windows installer 64 bits

**Additional context**
- When rollingback to 1.7.1 and unchecking the box to check for updates, the issue is resolved.
- The server is on version 10.8.9 (Docker on Synology NAS)
- All other platforms (i.e: Chrome, Brave, Jellyfin for iPhone) work as intented
[log_20230214.log](https://github.com/jellyfin/jellyfin-media-player/files/10733215/log_20230214.log)

**Comment by iwalton3** [comment] 2023-02-14 14:32
I need the log file here: https://github.com/jellyfin/jellyfin-media-player#log-file-location

**Comment by snozinho** [comment] 2023-02-14 15:01
> I need the log file here: https://github.com/jellyfin/jellyfin-media-player#log-file-location

[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10733675/JellyfinMediaPlayer.log)

**Comment by iwalton3** [comment] 2023-02-14 15:06
You are indeed having the same issue. Evidently ffmpeg doesn't support the cipher suites that your reverse proxy is configured to use.

**Comment by snozinho** [comment] 2023-02-14 15:15
Is there something we can do on our end or will a future update solve that issue? If not, does this mean we are "doomed" to keep the 1.7.1 forever?

**Comment by iwalton3** [comment] 2023-02-14 17:26
You'll have to figure out how to reconfigure your reverse proxy to allow a supported cipher suite.

**Comment by snozinho** [comment] 2023-02-14 21:24
@iwalton3 @1p1eq11 and anyone wondering, i found out!

In DSM 7.1, go to: Control Panel > Security > Advanced > **TLS/SSL Profile Level**

Set default parameters to: **Modern Compatibility**

Next, in Custom Settings below, set **System Default** to: _**Intermediate compatibility**_

I don't know why but setting only the jellyfin reverse proxy to _intermediate compatibility_ won't work right away, but I guess letting all other settings to _Modern compatibility_ is still a safe thing to set. If any expert can provide a better answer, I'll edit my post :)  

![image](https://user-images.githubusercontent.com/121609233/218866279-1afa7935-f39e-45d1-8976-4bb4238ad794.png)

**Comment by NotSaifA** [comment] 2023-02-14 22:28
Setting the minimum TLS version to 1.2 instead of 1.3 fixed it for me. It still does not explain why ffmpeg worked fine with TLS 1.3 before but stopped working after the update.

**Comment by NotSaifA** [comment] 2023-02-15 04:36
Reverting MPV to the previously used version (20211212-git-0e76372) solves the issue. @iwalton3 was there a reason behind upgrading MPV to the latest version?

**Comment by iwalton3** [comment] 2023-02-15 04:38
Yes people were asking for the upgraded version for a variety of reasons and it is usually good practice to keep up with these version changes.

**Comment by iwalton3** [comment] 2023-02-15 04:54
I think the issue was caused by upstream changing from libressl to mbedtls. https://github.com/shinchiro/mpv-winbuild-cmake/commit/358b4a3ad0a942105643fa135e723442ca7321dd

You could test this by trying a version older than the date of the referenced commit. This doesn't make much sense to me though since they are on the latest mbedtls which support TLS 1.3. Maybe talk to upstream about why TLS 1.3 doesn't seem to work? I'd prefer not to fork upsteam to fix TLS.

**Comment by iwalton3** [comment] 2023-03-04 06:03
I made an MPV build with libressl compiled in again: https://github.com/iwalton3/mpv-winbuild-cmake/releases/tag/v20230304-git-362256e

Please let me know if running the latest build works to resolve this issue: https://github.com/jellyfin/jellyfin-media-player/suites/11345988376/artifacts/583190784

**Comment by snozinho** [comment] 2023-03-04 16:37
hi @iwalton3 !

I tried to revert to TLS 1.3 after installing the JMP version you sent me (https://github.com/jellyfin/jellyfin-media-player/suites/11345988376/artifacts/583190784) and it works perfectly now.

Although, I put it back to TLS 1.2 until an update is rolled out, just for convenience's sake, but problem solved, totally 👍

**Comment by iwalton3** [comment] 2023-03-06 23:31
Sounds good. This will be fixed in the next release then.

**Closed by iwalton3** 2023-03-06 23:31 UTC
Labels: bug
