### ISSUE TITLE
Keyboard media keys not working on Windows 11

### ISSUE THREAD

**Issue by SgtTacooo** [jellyfin/jellyfin-media-player#287] opened 2022-07-24 08:38 UTC
Windows 11 doesn't allow the dedicated keyboard media keys (or emulated ones) to control Jellyfin Media Player. Worked perfectly fine on Windows 10, still works fine on other media players. Seems like a huge bug.

On rare occasions it will work for the play/pause, previous track and next track buttons but this is few and far between. Never have I seen it work with the stop key. Doesn't matter if the client is focused or not.

Keys;
Next track 0xB0
Previous track 0xB1
Stop track 0xB2
Play/Pause 0xB3

**Comment by fourstepper** [comment] 2023-06-12 14:32
Duplicate of https://github.com/jellyfin/jellyfin-media-player/issues/3

**Comment by sevenrats** [comment] 2023-12-31 21:48
thank you @fourstepper

**Closed by sevenrats** 2023-12-31 21:48 UTC
