### ISSUE TITLE
Portable build/Portable build instructions

### ISSUE THREAD

**Issue by whiteowl3** [jellyfin/jellyfin-media-player#189] opened 2022-01-02 02:54 UTC
Portable build instructions would be rad.

**Comment by iwalton3** [comment] 2022-01-02 02:55
What are you trying to build for? Ironically the best build instructions may be in the GitHub Actions or Flatpak files.

**Comment by whiteowl3** [comment] 2022-01-02 03:30
i'd really like portable builds for windows and linux, such that jellyfinmediaplayer, and 'Jellyfin Media Player' are kept in the local archive/directory.  ill check out the actions and see how far i get.

**Comment by iwalton3** [comment] 2022-01-02 03:32
Oh… I thought “portable” as in running in another OS. I know that JMP requires some .net files but otherwise *should* work in a folder.

**Comment by whiteowl3** [comment] 2022-01-02 03:35
no i mean "portable" as in the application could be on a thumb drive and work on multiple host machines.  I started manipulating install paths and quickly made a difficult mess for myself.  if you have any insight to offer id appreciate it.

**Comment by iwalton3** [comment] 2022-01-02 03:36
I would suggest trying to build the application and copy the program and not the installer

**Comment by whiteowl3** [comment] 2022-01-02 03:38
ok yeah that seems obvious.  sorry I saw this and went baby mode immediately:
![image](https://user-images.githubusercontent.com/71030468/147865438-b791efcf-5f9a-44f0-82fc-9441403e98e0.png)

**Comment by burnedvpn** [comment] 2022-01-07 11:28
This is a feature I'd really like to see as well. I will look into the GitHub Actions and Flatpak files as mentioned above.
I opened a similar issue #158 with my reasoning for this request.

**Comment by sevenrats** [comment] 2023-12-31 21:44
duplicate of #158

**Closed by sevenrats** 2023-12-31 21:44 UTC
Labels: enhancement
