### ISSUE TITLE
Would you consider having a new build with the latest release of MPV

### ISSUE THREAD

**Issue by EricChan1989** [jellyfin/jellyfin-media-player#529] opened 2023-12-01 07:11 UTC
Dear Developer,

Since MPV media player windows version has a new release, would you consider release a new build of JMP?

I am currently having some decoding issues of H265 using JMP, which is the image mosaic randomly.
However, if using something else to play the videos like potplayer or even Jellyfin server with Nvidia transcoding (play the video on the website), it works properly.

I guess that the update of MPV may be helpful on this issue.

Thanks.

**Comment by sevenrats** [comment] 2023-12-17 17:43
@EricChan1989 Thank you for this report. My instinct is to close this as a non-bug because of the feature request title but, if you would like to preserve it as a report for the mosaic issue, please update the title so that it is a bug report and not a feature request.

**Comment by iwalton3** [comment] 2023-12-17 17:46
This is planned for the next release. I ran into a snag where the process I was doing to build MPV from source with TLS that is actually working was failing, so it needs some work still.

**Comment by iwalton3** [comment] 2023-12-17 18:07
Update upstream fixed their TLS situation (switched back to openssl) so I don't need to build MPV from source anymore!

**Comment by sevenrats** [comment] 2023-12-17 20:01
closing this non bug as a duplicate of every other request for a new release, aggregating them all under #497 because it has the most info in it.

**Closed by sevenrats** 2023-12-17 20:01 UTC
Labels: enhancement
