### ISSUE TITLE
support m1 macs

### ISSUE THREAD

**Issue by steelersfan7** [jellyfin/jellyfin-media-player#99] opened 2021-05-27 17:56 UTC
This is just a feature request to target the new mac m1(arm) build.  It can run through the rosetta2 layer, but of course that has issues anytime your not running natively.

**Comment by thomaschampagne** [comment] 2021-05-28 19:14
Yes same ! A M1 arm version would be awesome.

Ask for help if you need anything (test, build, etc...)

**Comment by esmorun** [comment] 2021-06-07 17:27
I would love to see this as well. I tried it trough rosetta but the video freezes every second.

**Comment by yxwangcs** [comment] 2021-07-20 04:55
I think this is a duplicate of https://github.com/jellyfin/jellyfin-media-player/issues/19.

We still need to wait for QT 6.2 to come out with M1 support first ([scheduled to release at the end of this September](https://wiki.qt.io/Qt_6.2_Release)). Then we need to migrate the current codebase to QT 6, after that we need to fix the build config for arm64 platform. 

So, I think it might still take a while before there is a native version of Jellyfin media player on M1 Macs....

**Comment by torroa** [comment] 2021-10-31 16:08
Following..

**Comment by iwalton3** [comment] 2021-11-01 16:21
For those of you watching this issue, you may be interested to know I recently acquired an M1 MacBook.

**Comment by thomaschampagne** [comment] 2021-11-05 01:36
> For those of you watching this issue, you may be interested to know I recently acquired an M1 MacBook.

Great news !!!!!

**Comment by iwalton3** [comment] 2021-11-05 01:40
Yeah about that… I applied for a developer account and apparently they charged me the $100 and then decided to terminate it. I hadn’t even logged in.

No response from support of course. I’ll give it another day or two (I submitted another inquiry), but I think I am just going to have to leave this to someone else and leave the Apple ecosystem.

**Comment by iwalton3** [comment] 2021-11-05 01:41
Really frustrating too. Just when I was really starting to get into Apple stuff.

**Comment by thomaschampagne** [comment] 2021-11-05 18:02
It sucks. You can't develop without a developer account first? 

I also bought a M1 for a cross-platform Electron app I develop for this target (https://champagnethomas.medium.com/elevate-desktop-app-2021-update-9155fd74bb85)

I didn't applied to their program yet (when going stable). Their program is required for code signing your app for shipping. But you and early adopters of your mac version can install a non-signed dmg before everything works fine.

Hope you will get your refund !

**Comment by iwalton3** [comment] 2021-11-05 18:13
> You can't develop without a developer account first?

I am hesitant to invest my time in any platform I have been banned from… Speaking of they are apparently looking at my support case but haven’t made a decision yet.

The best outcome would be I am able to stick with Apple as other than this issue I have been a happy customer.

**Comment by steelersfan7** [comment] 2021-11-05 20:08
Hope Apple can resolve it! Let us know if they resolve it.

**Comment by thomaschampagne** [comment] 2021-11-06 15:46
Have you been refund?

**Comment by iwalton3** [comment] 2021-11-07 17:54
I got a response that they are looking into the issue, but I haven't gotten anything definitive yet. I will only pursue a refund if I run out of time or they give me a definitive response.

Needless to say I have been pretty happy with Apple and have bought a lot of their products, so I really would rather not drop Apple because of this.

**Comment by iwalton3** [comment] 2021-11-08 14:24
They have banned me without providing any reason and said they will not process any appeals. As a result, I will not give them another dollar of my money, will switch away from all their products, and will not be providing any support or endorsement for them ever again.

**Comment by zhaofengli** [comment] 2021-11-15 07:45
Since the "wontfix" tag was added to this and other related issues, I assume it has become the "official" stance of Jellyfin rather than that of an individual contributor? While I sympathize with @iwalton3's situation, this comes off as a bit odd.

**Comment by joshuaboniface** [comment] 2021-11-15 07:52
>I assume it has become the "official" stance of Jellyfin rather than that of an individual contributor?

@iwalton3 is the official developer of this app, under the Jellyfin umbrella. If he can't or won't develop for a particular platform, then it's unlikely to be done unless someone else is willing to do it. Perhaps we can leverage the team's Apple account (if we have one, cc @anthonylavado) but failing that, it is what it is.

**Comment by zhaofengli** [comment] 2021-11-15 07:53
@joshuaboniface Cool, thanks for the clarification.

**Comment by esmorun** [comment] 2021-11-15 09:04
I'm a bit lost here, I sympathize with @iwalton3, but why are we discussing Apple developer accounts? No need so sign the app or put it on the app store.

The goal here is just to succesfully compile the app for Apple silicon.
https://www.qt.io/blog/qt-on-apple-silicon

**Comment by dkanada** [comment] 2021-11-15 10:43
@joshuaboniface was only trying to say that @iwalton3 has decided not to implement this feature and he is the only one working on this client right now. If someone else decides to open a pull request that adds support in a way that doesn't impact the entire codebase it would likely be merged, but otherwise there are no official plans to implement M1 support.

**Comment by iwalton3** [comment] 2021-11-15 13:03
I will not be working on it as I have sold the M1 max I bought and am banned from the developer program.

It is particularly problematic because GitHub only has CI/CD for Intel.

Of course if anyone can find a solution to this then fine. But I can’t build, support, or release for this platform.

**Comment by dominikscha** [comment] 2021-11-20 18:05
Hi all
I was playing a bit with compilation settings to run it natively on Apple Silicon (M1). Now, it is basically running without HW acceleration. Still have a problem ffmpeg if I turn HW. I let you know about my progress.

**Comment by yxwangcs** [comment] 2021-11-20 18:45
Out of curiosity did you compile a universal binary? QT officially supports
it since 6.2 but I’m curious how it works on QT 5.

**Comment by iwalton3** [comment] 2021-11-20 18:46
If someone is interested in working on this feel free to re-open the issue

**Comment by xternaal** [comment] 2021-11-26 04:42
Hmm - seems like they don't want allow a competitor to apple tv/tv+
Very poor form

**Comment by iwalton3** [comment] 2021-11-26 04:43
No that has nothing to do with this. Also Infuse is available on iOS and TV OS which supports Jellyfin.

**Comment by axeII** [comment] 2022-04-03 15:22
@dominikscha Can you please share your compilation settings? I'm unable to build Jellyfin player for apple silicon:

```
...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Thanks

**Comment by dominikscha** [comment] 2022-04-03 15:58
> @dominikscha Can you please share your compilation settings? I'm unable to build Jellyfin player for apple silicon:
> 
> ```
> ...
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Thanks

Hi Axell

I used the following in build.macos:
dotnet publish Jellyfin.Server --configuration Release --self-contained --runtime osx-arm64 --output dist/jellyfin-server_${version}/ "-p:DebugSymbols=false;DebugType=none;UseAppHost=true"

As Jellyfin is using ffmpeg for transcoding, you could also experiment with getting a arm64 version of ffmpeg. I found one on Homebrew.

**Comment by whiteowl3** [comment] 2022-10-06 03:12
Is this build method still working? Considering purchasing apple silicon.
Can this become an Apple Silicon thread and include the M2, or should M2 become a separate issue?

**Comment by captainhook** [comment] 2022-10-20 00:38
> I will not be working on it as I have sold the M1 mac I bought and am banned from the developer program.

Good old Apple and Apple ecosystem.

**Comment by dominikscha** [comment] 2022-10-20 06:49
> 

I didn't try it recently. My server is still running on an Intel Mac. I am waiting for Mac mini M2 before I migrate.

**Comment by GuyKh** [comment] 2023-01-10 12:23
It's 2023... no news yet?

**Comment by iwalton3** [comment] 2023-01-10 12:27
Unless someone else makes it work and PRs the changes there are no plans to support this

**Comment by Vinu-Suhas** [comment] 2023-02-02 03:29
i have m1 mac can anyone how to compile the app for macbook?

**Comment by sevenrats** [comment] 2023-02-13 19:42
this compiles on m1 and m2, but there are two issues i cannot fix.  1) i just gutted default mpv tls settings because i don't cpp good enough to fix the error.  2) something is up with mpvVideoPlayer.js now.  z indexes are screwed up. the video directplays properly, but the video is not properly displayed.  its somewhere in the stack though, and you can hear it playing.  if somebody can fix those two errors its essentially ready.
https://github.com/sevenrats/jellyfin-media-player/tree/qt6

**Comment by Vinu-Suhas** [comment] 2023-02-16 09:01
Also the intel jellyfin  Mac app has issues playing dolby vision files green and violet  colored .Please solve this issue also while updating it to arm64

**Comment by iwalton3** [comment] 2023-02-16 12:47
The next release will force transcode Dolby vision files, but please don't hijack issues as it makes the issue tracker unmanageable.

**Comment by sevenrats** [comment] 2024-01-04 19:36
this issue hasnt been updated in awhile so let me update you all:
its not a z index thing its a bug in Qt.
https://bugreports.qt.io/browse/QTBUG-111739
second, iwalton has implemented a workaround in the qt6 branch to move the video on top of the webview and resize it to reveal the webui.  this works but presents other problems such as concealing menus still.
third, you can actually build this on M1 and M2 using the qt@5 brew formula, which has now been patched for some apple silicon support. this seems to me to significantly improve performance over running pure intel binaries. some parts of the stack are probably still in intel code and I haven't checked, but the reason i didnt check is because I was highly satisfied with the performance.  i assume the primary benefit is from moving mpv over to native code.
finally, to the best of my knowledge apple silicon CI is still a long way away. if you know of a way to provide apple silicon builds in an open way, mention it.  at that point, an apple native build will close this issue.

**Comment by szlend** [comment] 2024-01-06 15:41
It seems to build fine on Nix `aarch64-darwin` ([link](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/jellyfin-media-player/default.nix)) which should be completely arm-based. However it's not able to display anything, failing with:

```
Error loading client, this is bad and should not happen
You can try to reload or head to our support page

Actual error:
  [0]

Provide the logfile as well.
```


```
[0106/163508.969968:ERROR:icu_util.cc(251)] Couldn't mmap icu data file
[17534:126467:0106/163509.004600:ERROR:gl_context_cgl.cc(118)] Error creating context.
[0106/163509.481610:ERROR:icu_util.cc(251)] Couldn't mmap icu data file
```

Seems like it's not able to create an OpenGL context at all, for whatever reason.

**Comment by sevenrats** [comment] 2024-01-06 16:28
@szlend whatever icu_util.cc is has nothing to do with us as far as I know. We don't maintain the nix package, and its not clear what code its using to support aarch64. frankly you should open this report with NixOS.

**Comment by gnattu** [comment] 2024-03-06 00:46
For me to make the Apple Silicon build happen, I want to know the "magic" this installs the dylibs.

Which script is doing such thing?

It compiles fine with the homebrew libs, , but the dylibs referenced in rpath is not installed into `Frameworks` folder, makes the generated binary not runnable, the non-distributable one runs okay.

**Comment by sevenrats** [comment] 2024-03-06 12:17
@gnattu #536 which is a variation on  scripts/fix-install-names.py
manipulate these scripts to pull in whatever you need. If you have used qt@5 through brew, which is easiest these days, those will need to be pulled in first (dont think I added them to the version in #536

**Comment by gnattu** [comment] 2024-03-06 15:56
@sevenrats I already modified it in #571 , but I'm not sure if it will affect the current Intel builds as CI will not run on pull requests.

**Comment by gnattu** [comment] 2024-03-11 11:39
Hello forks, if you cannot wait, you can try the artifact from this build:
https://github.com/gnattu/jellyfin-media-player/actions/runs/8231945672

This build is not notarized like the release version, so macOS would warn you when you open it, you need to go to Settings->Privacy & Security and allow it.

The Intel build is broken for now as the path changes and I guess I need to migrate that build to use homebrew's qt as well.

Windows and some ubuntu target failed due to various dependency no longer available and is not related to my changes.

**Comment by davidawad** [comment] 2024-03-25 19:02
👋 Just confirming that downloading and unzipping the build artifact worked for me. 

<img width="1194" alt="image" src="https://github.com/jellyfin/jellyfin-media-player/assets/4019054/2280fa1c-4a90-48c0-b4b4-52ee5809f5fe">

**Closed** 2024-05-13 21:58 UTC
Labels: enhancement
