### ISSUE TITLE
Uninterrupted playback

### ISSUE THREAD

**Issue by s1m-e0n** [jellyfin/jellyfin-media-player#377] opened 2023-02-15 17:05 UTC
It would be really great if there weren't a pause/interruption between tracks when playing back an album or playlist. Much of the music I listen to is spread over multiple tracks.
Thank you all for your hard work :)
(P.S. also posted this to the android client issue board)

**Comment by iwalton3** [comment] 2023-02-16 01:33
Duplicate of #47

**Closed** 2023-02-16 01:34 UTC
Labels: enhancement
