### ISSUE TITLE
How to resume please

### ISSUE THREAD

**Issue by exalis86** [jellyfin/jellyfin-media-player#307] opened 2022-09-18 02:07 UTC
Hi everyone, I just installed this app on Pop OS and it works great, I can connect to my server (updated version) and start playback but I can't resume playback, it restarts at the beginning every time. I can't manually advance either.

I searched ~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/ellyfinmediaplayer.conf but I couldn't find anything that seems to match this.

Could someone help me please ?

![image](https://user-images.githubusercontent.com/95535070/190882523-49baf29b-17f4-4738-905c-82db72db9037.png)

**Comment by iwalton3** [comment] 2023-03-12 16:22
Duplicate of #174

**Closed by iwalton3** 2023-03-12 16:22 UTC
Labels: enhancement
