### ISSUE TITLE
flatpak version missing window decorations on gnome 40

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-media-player#60] opened 2021-04-22 20:31 UTC
```2021-04-22 22:17:28 [ INFO  ] Log.cpp @ 116 - Starting Jellyfin Media Player version: 1.4.1 build date: 2021-04-20 
2021-04-22 22:17:28 [ INFO  ] Log.cpp @ 117 -   Running on: KDE Flatpak runtime [5.11.12-300.fc34.x86_64] arch x86_64 
2021-04-22 22:17:28 [ INFO  ] Log.cpp @ 118 -   Qt Version: 5.15.3 [x86_64-little_endian-lp64] 
2021-04-22 22:17:28 [ WARN  ] Log.cpp @ 35 - "QObject::connect(SettingsSection, Unknown): invalid nullptr parameter" 
2021-04-22 22:17:28 [ INFO  ] ComponentManager.cpp @ 36 - Component: settings inited 
2021-04-22 22:17:28 [ INFO  ] InputMapping.cpp @ 113 - Loading inputmaps from: ":/inputmaps" 
2021-04-22 22:17:28 [ WARN  ] InputMapping.cpp @ 92 - Missing element 'idmatcher' from mapping file: ":/inputmaps/dualshock4-xbox-emulate.json" 
2021-04-22 22:17:28 [ INFO  ] InputMapping.cpp @ 113 - Loading inputmaps from: "/home/<user>/.var/app/com.github.iwalton3.jellyfin-media-player/data
/jellyfinmediaplayer/inputmaps" 
2021-04-22 22:17:28 [ INFO  ] InputComponent.cpp @ 54 - Successfully inited input: Keyboard 
2021-04-22 22:17:28 [ INFO  ] LocalJsonServer.cpp @ 33 - Listening to socket: "/tmp/pmp_inputSocket_.sock" 
2021-04-22 22:17:28 [ INFO  ] InputComponent.cpp @ 54 - Successfully inited input: socket 
2021-04-22 22:17:28 [ WARN  ] InputComponent.cpp @ 50 - Failed to init input: roku 
2021-04-22 22:17:28 [ INFO  ] InputSDL.cpp @ 207 - SDL found  0  joysticks 
2021-04-22 22:17:28 [ INFO  ] InputComponent.cpp @ 54 - Successfully inited input: SDL 
2021-04-22 22:17:28 [ ERROR ] InputLIRC.cpp @ 82 - LIRC Socket Error :  QLocalSocket::ServerNotFoundError 
2021-04-22 22:17:28 [ WARN  ] InputComponent.cpp @ 50 - Failed to init input: LIRC 
2021-04-22 22:17:28 [ INFO  ] ComponentManager.cpp @ 36 - Component: input inited 
2021-04-22 22:17:28 [ INFO  ] ComponentManager.cpp @ 36 - Component: system inited 
2021-04-22 22:17:28 [ ERROR ] ComponentManager.cpp @ 44 - Failed to init component: display
```
This is the only part that reports an error. Let me know if you want the whole thing.

**Describe the bug**
Window has no decorations, which makes it impossible to maximize, move or resize

**To Reproduce**
1: install+start flakpak according to https://flathub.org/apps/details/com.github.iwalton3.jellyfin-media-player
2: Notice the missing window decoration

**Expected behavior**
Window has decorations.

**Desktop (please complete the following information):**
 - OS: Fedora 34 (Gnome 40)
 - Installation Method : flatpak

**Comment by krutburken** [comment] 2021-04-22 20:38
maybe the same as https://github.com/jellyfin/jellyfin-media-player/issues/40

**Comment by iwalton3** [comment] 2021-04-22 21:02
This is almost certainly a duplicate of #40. If not ask me and I'll re-open it.

**Closed by iwalton3** 2021-04-22 21:02 UTC
Labels: bug

**Comment by krutburken** [comment] 2021-04-23 10:21
> This is almost certainly a duplicate of #40. If not ask me and I'll re-open it.

Yeah, sorry. I first noticed it after I made this issue.
