### ISSUE TITLE
Update notification buttons have no effect

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin-media-player#376] opened 2023-02-14 18:33 UTC
**Describe the bug**
The "Update available" notification stays open when clicking any of its buttons "Download" or "Ignore". It is impossible to dismiss the notification to see the servers' contents.

**To Reproduce**
1. Launch JMP when an update is available
2. Click either "Download" or "Ignore".

**Expected behavior**
Clicking "Ignore" or "Download" should have the appropriate effect.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.0

**Comment by iwalton3** [comment] 2023-02-14 23:24
Duplicate of #373

**Closed by iwalton3** 2023-02-14 23:24 UTC
Labels: bug
