### ISSUE TITLE
AV1 artifacting error

### ISSUE THREAD

**Issue by HannahBanana1312** [jellyfin/jellyfin-media-player#497] opened 2023-09-21 04:00 UTC
Four considerations:
 - Please do not open bug reports to ask questions. Use the Discussions feature instead.
 - Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
 - Please make sure that your issue is not being caused by errors in custom CSS or note that you are using custom CSS.
     - Notably, there have been instances of custom CSS breaking TV mode.
     - You can disable custom CSS under Display in the user settings.
 - Please provide logs. You can drag the log file into the issue to attach it.
     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
     - Linux: `~/.local/share/jellyfinmediaplayer/logs/`
     - Linux (Flatpak): `~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/`
     - macOS: `~/Library/Logs/Jellyfin Media Player/`

**Describe the bug**

When watching AV1 encoded files, there's artifacting and flickers, it looks like the next frame is overlaid onto the current frame. It does not show up when watching using MPC-HC directly. I would test on web but it hangs and won't direct play or transcode (tried Firefox and Edge)

**To Reproduce**
Watch a file encoded with AV1

**Expected behavior**
A normal viewing experience

**Screenshots**

![Frame 1](https://github.com/jellyfin/jellyfin-media-player/assets/36461227/4de18d30-0796-46c6-9909-1e889e8dcbcb)
![Frame 2](https://github.com/jellyfin/jellyfin-media-player/assets/36461227/841a151d-364e-44f9-89e1-cb74c900db20)
![Frame 3](https://github.com/jellyfin/jellyfin-media-player/assets/36461227/308b110a-5cfa-4073-a7dc-d2b7c35c0f2d)
![Frame 4](https://github.com/jellyfin/jellyfin-media-player/assets/36461227/55e994d9-9cf5-43bf-9dc0-b3732f2e6add)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 21H2 build 19044.3086
 - Version [e.g. 22] 1.9.1
 - Installation Method [e.g. windows installer] JellyfinMediaPlayer-1.9.1-windows-x64.exe 

**Additional context**
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/12679809/JellyfinMediaPlayer.log)

**Comment by felix920506** [comment] 2023-09-24 19:15
Possible duplicate of #460 ?

**Comment by xescure** [comment] 2023-10-06 17:55
> Possible duplicate of #460 ?

Possibly, but #460's visual problems don't resemble the usual presentation (rainbow artifacting) of this bug. I think it would be wise to hold off closing this, until the underlying problem is solved.

**Comment by xescure** [comment] 2023-10-06 18:02
It is most likely caused by an outdated video player dependency. `dav1d` introduced this bug at some point, but versions after [v1.2.1](https://code.videolan.org/videolan/dav1d/-/releases/1.2.1) should be alright.  Compiling the project with up-to-date MPV DLLs might fix it, but I have not tested it myself.

**Comment by solidsnake1298** [comment] 2023-11-11 05:10
I was not able to reproduce.  Neither in Ubuntu 22.04.3 LTS Desktop nor Windows 11 23H2.  Tried both AV1 HDR content and AV1 SDR content.

JMP 1.9.1
Server 10.8.12, Ubuntu 22.04.3 LTS Server
GPU AMD Radeon RX 6800
CPU Ryzen 7 5900X
![av1 sdr](https://github.com/jellyfin/jellyfin-media-player/assets/137357145/207d4447-dec3-4055-8b1c-ad72421dc582)
![av1 hdr](https://github.com/jellyfin/jellyfin-media-player/assets/137357145/3905f5f0-26e9-4aa2-b6db-fff61bb0908e)

**Comment by iwalton3** [comment] 2023-11-11 05:15
I heard it is fixed by updated MPV dlls. Unfortunately I now have to compile from source for Windows because the MPV version officially shipped has a TLS version that doesn't work correctly. I tried building it the other day but I have to hand patch the build scripts since they are broken.

**Comment by xescure** [comment] 2023-11-16 22:39
@solidsnake1298 it's definitely not all content. AFAIK it has something to do with the embedded grain in the video stream.

[Here](https://1drv.ms/u/s!As_YagEFqp5xuIURbyLrL7g651c1vg?e=HoqRzX)'s a really short clip that triggers the problem.

**Comment by solidsnake1298** [comment] 2023-11-17 14:10
> @solidsnake1298 it's definitely not all content. AFAIK it has something to do with the embedded grain in the video stream.
> 
> [Here](https://1drv.ms/u/s!As_YagEFqp5xuIURbyLrL7g651c1vg?e=HoqRzX)'s a really short clip that triggers the problem.

I will add this to my test library tonight and report back.

**Comment by solidsnake1298** [comment] 2023-11-18 17:22
@xescure The file you provided did not trigger what you described on my system.  Side note, what is this clip from?

![image](https://github.com/jellyfin/jellyfin-media-player/assets/137357145/e8e74c34-a4e9-47bb-b278-a469bcd67e5e)

**Comment by xescure** [comment] 2023-11-18 17:56
@solidsnake1298 Are you on Windows? I can try to replicate it on other computers, but I don't see why it wouldn't show up with the same file, on the same OS *(Windows 10/11)* and same build *([v1.9.1](https://github.com/jellyfin/jellyfin-media-player/releases/download/v1.9.1/JellyfinMediaPlayer-1.9.1-windows-x64.exe))*

Also, the clip I provided wasn't the best way to show it [this](https://1drv.ms/u/s!As_YagEFqp5xuIUUZ_Q6dvLi_N2pxw?e=SHFdZa) should be much better.

Here's some extra background info:

![image](https://github.com/jellyfin/jellyfin-media-player/assets/12898109/dcffae30-d3b5-473b-9e78-1e6c79456a39)

![image](https://github.com/jellyfin/jellyfin-media-player/assets/12898109/af58ed93-4c7a-4006-bc0b-ddb117901523)


p.s.: The clip is from [Frieren](https://myanimelist.net/anime/52991/Sousou_no_Frieren)

**Comment by solidsnake1298** [comment] 2023-11-18 18:00
THAT file triggered it for me.

![image](https://github.com/jellyfin/jellyfin-media-player/assets/137357145/fb41d70d-0c88-47d8-b86d-565f70ddb1d0)

**Comment by sevenrats** [comment] 2023-12-17 19:52
looks like this is confirmed and ready for a fix. this issue will be closed by an updated release.

**Comment by shaunvaidyan** [comment] 2024-01-19 21:45
I'm still having this exact issue while direct playing av1 encoded files in the Jellyfin app. I'm using the Jellyfin windows app version 1.9.1 on Windows 11 Pro 22621.3007 with an AMD Ryzen 7800XT and a Radeon 7900XTX

**Comment by Malumen** [comment] 2024-03-08 13:13
Confirm I'm also experiencing this on a NAS running in docker.

**Comment by hydrtd** [comment] 2024-04-11 11:56
Same issue on 1.9.1 windows 11 pro 22H2 22621.3007 RX6500XT graphics card. I downgraded to release 1.8.1 and that fixed it.

**Comment by fatexs** [comment] 2024-04-11 19:00
Is there any clips to reproduce not hosted on onedrive? That site is looping for me...

I have used a mpv.dll build from shinchiro (mpv-dev-x86_64-v3-20231231-git-abc2a74.7z) to fix another issue unrelated to av1 and I have never seen this, although I have seen plenty of AV1
Also that mpv build works without any issues for me so you can maybe try that one.

**Comment by solidsnake1298** [comment] 2024-05-18 00:41
@xescure Can you repost the one clip I stated triggered the AV1 chroma bug?  I cleared out all my test libraries for a server rebuild and need a known "bad" clip to test JMP 1.10.

**Comment by Volkor3-16** [comment] 2024-05-18 07:55
My mate who had this bug cannot replicate this on JMP 1.10

**Closed** 2024-05-18 14:32 UTC
Labels: bug
