### ISSUE TITLE
Include releases in Jellyfin repo

### ISSUE THREAD

**Issue by matthewpritchett** [jellyfin/jellyfin-media-player#550] opened 2024-01-20 17:09 UTC
**Is your feature request related to a problem? Please describe.**
When using the deb file, updates are difficult as they must be done manually.

**Describe the solution you'd like**
Include the Debian and Ubuntu deb releases in the official Jellyfin apt repo

**Describe alternatives you've considered**
Flatpack

**Additional context**

**Comment by matthewpritchett** [comment] 2024-02-04 13:18
@iwalton3 Let me know if there’s anything I can do to help out on this, but I’m guessing since it involves the Jellyfin Official Repo that it’ll be someone else that is able to have permissions for it. Thanks!

**Comment by n-peugnet** [comment] 2024-07-07 16:11
This is a duplicate of #171

**Closed** 2024-07-07 20:36 UTC
Labels: enhancement
